### ISSUE TITLE
Combine "mapbox-gl-plugins" repo and GL JS's "docs/_posts/plugins"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-plugins#17]
See https://github.com/mapbox/mapbox-gl-js/issues/3076

**Comment by lbud** [comment]
Can we delete this repo then? @lucaswoj @mourner

**Comment by lucaswoj** [comment]
Go for it @lbud! ♻️

**Comment by lbud** [comment]
oh jk I don't have permissions to modify this repo settings 😿 @tristen or @lucaswoj do either of you?
