### ISSUE TITLE
Add mapbox-gl-draw

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-plugins#2]
@kelvinabrokwa when [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw) is in a stable place it should be added as a plugin to this repo so there's a cdn link to it, Some [setup instructions are here](https://github.com/mapbox/mapbox-gl-plugins#setup).

**Comment by mollymerp** [comment]
done in https://github.com/mapbox/mapbox-gl-plugins/commit/727efc1d5dec42fe618411a2705dad539e48ecf5

**Comment by kelvinabrokwa** [comment]
tnx @mollymerp, u the real mvp
